#!/usr/bin/env python3
"""
Resolve fallback ANR RNSR units through lead researchers in the INRAE directory.

Run after scripts/build_data.py has produced a first data/inrae_anr_projects.json:
partners still using the ANR label fallback are queried in the public people
directory, then their current "Unité de rattachement" is mapped back to the
structure cache generated by enrich_inrae_structures.py.
"""

import argparse
import json
import re
import time
import unicodedata
import urllib.parse
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path

from enrich_inrae_structures import (
    BASE_URL,
    clean_html,
    fetch,
    parse_links,
)

BASE_DIR = Path(__file__).resolve().parent.parent
PROJECTS_JSON = BASE_DIR / "data" / "inrae_anr_projects.json"
STRUCTURES_JSON = BASE_DIR / "data" / "inrae_structures.json"
OUTPUT = BASE_DIR / "data" / "inrae_lead_units.json"

INRAE_FAMILY = {"INRAE", "IRSTEA", "CEMAGREF"}
LEAD_RESOLVABLE_SOURCES = {"anr_partner_label", "annuaire_lead_person"}


def log(message):
    print(message, flush=True)


def normalize_person(value):
    text = clean_html(value).upper()
    text = unicodedata.normalize("NFKD", text)
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    replacements = {
        "ÇC": "C",
        "Œ": "OE",
        "Æ": "AE",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    text = re.sub(r"[^A-ZÀ-ÖØ-Þ0-9]+", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def load_json(path):
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def load_existing_matches(path):
    if not path.exists():
        return [], set()
    payload = load_json(path)
    unresolved_rnsr = {
        rnsr
        for rnsr in payload.get("unresolvedRnsr", [])
        if rnsr
    }
    return payload.get("matches", []), unresolved_rnsr


def load_structures_by_id(path):
    payload = load_json(path)
    return {
        str(structure.get("id")): structure
        for structure in payload.get("structures", [])
        if structure.get("id")
    }


def collect_fallback_leads(projects_path, source_filter):
    payload = load_json(projects_path)
    leads = {}
    for project in payload.get("projects", []):
        for partner in project.get("partners", []):
            if partner.get("entity") not in INRAE_FAMILY:
                continue
            if partner.get("unitSource") not in source_filter:
                continue
            rnsr = partner.get("rnsr")
            lead_name = partner.get("leadName")
            lead_first_name = partner.get("leadFirstName")
            if not rnsr or not lead_name or not lead_first_name:
                continue
            key = (rnsr, lead_first_name, lead_name)
            item = leads.setdefault(key, {
                "rnsr": rnsr,
                "leadFirstName": lead_first_name,
                "leadName": lead_name,
                "projects": set(),
                "fallbackLabel": partner.get("unitName") or partner.get("name") or "",
            })
            item["projects"].add(project.get("id"))

    return [
        {**item, "projects": sorted(item["projects"])}
        for item in leads.values()
    ]


def post_person_search(session, last_name, first_name):
    html = fetch("/personnes", session=session)
    token_match = re.search(
        r'name="personne_search_form\[_token\]" value="([^"]+)"',
        html,
    )
    if not token_match:
        raise RuntimeError("Could not find people search CSRF token")

    body = urllib.parse.urlencode({
        "personne_search_form[nom]": last_name,
        "personne_search_form[prenom]": first_name,
        "personne_search_form[codeCentre]": "",
        "personne_search_form[_token]": token_match.group(1),
        "personne_search_form[submit]": "Rechercher",
    }).encode("utf-8")
    return fetch("/personnes", method="POST", body=body, session=session)


def person_title(html):
    title_match = re.search(r'<h1 class="hero__title">\s*(.*?)</h1>', html, re.I | re.S)
    return clean_html(title_match.group(1)) if title_match else ""


def person_matches(title, last_name, first_name):
    title_norm = normalize_person(title)
    last_norm = normalize_person(last_name)
    first_norm = normalize_person(first_name)
    if not title_norm or not last_norm:
        return False
    first_token = first_norm.split()[0] if first_norm else ""
    return last_norm in title_norm and (not first_token or first_token in title_norm)


def person_links_from_results(html, last_name, first_name):
    expected_last = normalize_person(last_name)
    expected_first = normalize_person(first_name).split()[0] if normalize_person(first_name) else ""
    links = []
    pattern = re.compile(r'<a\b[^>]*href="(/personne/[^"]+)"[^>]*>(.*?)</a>', re.I | re.S)
    for match in pattern.finditer(html):
        label = clean_html(match.group(2))
        label_norm = normalize_person(label)
        if expected_last in label_norm and (not expected_first or expected_first in label_norm):
            links.append(match.group(1))
    return links


def affiliation_structure_ids(person_html):
    match = re.search(
        r"<dt>\s*Unité de rattachement.*?</dt>\s*<dd>(.*?)</dd>",
        person_html,
        re.I | re.S,
    )
    if not match:
        return []
    ids = []
    seen = set()
    for link in parse_links(match.group(1)):
        if link["id"] not in seen:
            seen.add(link["id"])
            ids.append(link["id"])
    return ids


def query_person_affiliations(lead):
    import http.cookiejar

    session = http.cookiejar.CookieJar()
    html = post_person_search(session, lead["leadName"], lead["leadFirstName"])
    title = person_title(html)
    candidates = []

    if person_matches(title, lead["leadName"], lead["leadFirstName"]):
        candidates.append({
            "personName": title,
            "personUrl": "",
            "html": html,
        })
    else:
        for link in person_links_from_results(html, lead["leadName"], lead["leadFirstName"]):
            person_html = fetch(link, session=session)
            person_name = person_title(person_html)
            if person_matches(person_name, lead["leadName"], lead["leadFirstName"]):
                candidates.append({
                    "personName": person_name,
                    "personUrl": f"{BASE_URL}{link}",
                    "html": person_html,
                })

    affiliations = []
    for candidate in candidates:
        for structure_id in affiliation_structure_ids(candidate["html"]):
            affiliations.append({
                "personName": candidate["personName"],
                "personUrl": candidate["personUrl"],
                "structureId": structure_id,
            })
    return affiliations


def build_matches(leads, structures_by_id, sleep):
    raw_matches = []
    for index, lead in enumerate(leads, start=1):
        affiliations = query_person_affiliations(lead)
        for affiliation in affiliations:
            structure = structures_by_id.get(affiliation["structureId"])
            if not structure:
                continue
            raw_matches.append({
                **lead,
                **affiliation,
                "structureRnsr": structure.get("rnsr", ""),
                "structure": structure,
            })
        log(f"  [{index:02d}/{len(leads):02d}] {lead['leadFirstName']} {lead['leadName']}: {len(affiliations)} affiliation(s)")
        time.sleep(sleep)

    grouped = defaultdict(list)
    for match in raw_matches:
        grouped[match["rnsr"]].append(match)

    selected = []
    for rnsr, matches in sorted(grouped.items()):
        counts = Counter(match["structureId"] for match in matches)
        best_id = counts.most_common(1)[0][0]
        best = next(match for match in matches if match["structureId"] == best_id)
        structure = best.pop("structure")
        selected.append({
            "rnsr": rnsr,
            "leadFirstName": best["leadFirstName"],
            "leadName": best["leadName"],
            "personName": best["personName"],
            "personUrl": best["personUrl"],
            "projects": best["projects"],
            "fallbackLabel": best["fallbackLabel"],
            "structureId": structure.get("id", ""),
            "structureRnsr": structure.get("rnsr", ""),
            "unitName": structure.get("unitName", ""),
            "unitLabel": structure.get("label", ""),
            "unitType": structure.get("unitType", ""),
            "unitCode": structure.get("unitCode", ""),
            "unitAcronym": structure.get("unitAcronym", ""),
            "unitCentre": structure.get("centre", ""),
            "unitDepartment": structure.get("departmentPilot", ""),
            "unitDepartmentCode": structure.get("departmentPilotCode", ""),
            "unitDepartmentCopilots": structure.get("departmentCopilots", []),
            "unitUrl": structure.get("url", ""),
        })
    return selected


def merge_matches(existing, new):
    merged = {}
    for match in existing:
        rnsr = match.get("rnsr")
        if rnsr:
            merged[rnsr] = match
    for match in new:
        rnsr = match.get("rnsr")
        if rnsr:
            merged[rnsr] = match
    return [merged[rnsr] for rnsr in sorted(merged)]


def write_output(path, matches, unresolved_rnsr=None):
    output = {
        "generatedAt": date.today().isoformat(),
        "source": f"{BASE_URL}/personnes",
        "unresolvedRnsr": sorted(unresolved_rnsr or []),
        "matches": matches,
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(output, handle, ensure_ascii=False, indent=2)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--projects", default=str(PROJECTS_JSON))
    parser.add_argument("--structures", default=str(STRUCTURES_JSON))
    parser.add_argument("--output", default=str(OUTPUT))
    parser.add_argument("--sleep", type=float, default=0.08)
    parser.add_argument("--missing-only", action="store_true", help="Query only unresolved fallback RNSR not already in the cache")
    args = parser.parse_args()

    output_path = Path(args.output)
    existing_matches, existing_unresolved = load_existing_matches(output_path) if args.missing_only else ([], set())
    existing_rnsr = {
        match.get("rnsr")
        for match in existing_matches
        if match.get("rnsr")
    }
    source_filter = {"anr_partner_label"} if args.missing_only else LEAD_RESOLVABLE_SOURCES
    leads = collect_fallback_leads(Path(args.projects), source_filter)
    if args.missing_only:
        leads = [
            lead
            for lead in leads
            if lead["rnsr"] not in existing_rnsr and lead["rnsr"] not in existing_unresolved
        ]
    structures_by_id = load_structures_by_id(Path(args.structures))

    log(f"Fallback lead queries: {len(leads)}")
    if args.missing_only:
        log(f"Existing lead matches : {len(existing_matches)}")
        log(f"Known unresolved RNSR: {len(existing_unresolved)}")
    log(f"Known structures     : {len(structures_by_id)}")

    if args.missing_only and not leads and output_path.exists():
        log("No new fallback lead to query; keeping the existing lead-unit cache.")
        return

    queried_rnsr = {lead["rnsr"] for lead in leads}
    matches = build_matches(leads, structures_by_id, args.sleep)
    matched_rnsr = {
        match.get("rnsr")
        for match in matches
        if match.get("rnsr")
    }
    unresolved_rnsr = queried_rnsr - matched_rnsr
    if args.missing_only:
        unresolved_rnsr = (existing_unresolved | unresolved_rnsr) - matched_rnsr
        matches = merge_matches(existing_matches, matches)

    write_output(output_path, matches, unresolved_rnsr)

    log("")
    log(f"OK: {output_path} ({len(matches)} RNSR resolved through leads)")


if __name__ == "__main__":
    main()
